<?php

/**
 * Webservice API2 renderer of HTML type model
 *
 * @category   Mage
 * @package    Mage_Api2
 * @author     Sven Varkel <sven@mageflow.com>
 */
class Mageflow_Connect_Model_Api2_Renderer_Html
    implements Mage_Api2_Model_Renderer_Interface
{
    /**
     * Adapter mime type
     */
    const MIME_TYPE = 'text/html';

    /**
     * Render API resource as HTML
     *
     * @param mixed $data
     *
     * @return string
     */
    public function render($data)
    {
        $content = $this->_renderArray($data);
        //TODO create proper HTML writer n' templates n' stuff. Sven
        $html
            = <<<HTML
<html>
<head>
    <title>MageFlow API documentation</title>
    <style type="text/css">
        body{
            font-family: sans-serif;
            font-size: 12px;
        }
    </style>
</head>
<body>
$content
</body>
</html>
HTML;
        return $html;
    }


    /**
     * Renders array elements to HTML
     *
     * @param \Mage_Core_Model_Config_Element $data
     *
     * @return string
     */
    private function _renderArray($data)
    {
        $html = "<h2>API Resources</h2>";
        $html .= '<ul>';
        if ($data instanceof Mage_Core_Model_Config_Element) {
            foreach ($data->children() as $name => $element) {
                $html .= sprintf("\t<li>\n%s\n", $name);
                $html .= "<ul>\n";
                foreach ($element->routes->children() as $routeEntity) {
                    $html .= sprintf(
                        "\t\t<li>
                        <a href='/api/rest%1\$s'>/api/rest%1\$s</a>
                        </li>\n",
                        $routeEntity->route
                    );
                }
                $html .= "</ul>\n";
                $html .= "\t</li>\n";
            }
        }
        $html .= '</ul>';
        return $html;
    }

    /**
     * Get MIME type generated by renderer
     *
     * @return string
     */
    public function getMimeType()
    {
        return self::MIME_TYPE;
    }
}
